---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Deploy index.html files
  template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
    mode: 0444
  with_items:
    - { hostname: "vm1", fqdn: "{{ ansible_fqdn }}" }
    - { hostname: "vm2", fqdn: "{{ ansible_fqdn }}" }
    - { hostname: "vm3", fqdn: "{{ ansible_fqdn }}" }
  notify: Restart Apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes
